import { type NextPage } from "next";
import Head from "next/head";


import { signIn, signOut, useSession } from "next-auth/react";
import VideoGrid from "../components/videoGrid"
import { api } from "~/utils/api";
import Header from "~/components/Header/Header";

const Home: NextPage = () => {
  const video = api.video.videoList.useQuery()
  const userVideo = api.video.userVideoList.useQuery()
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="bg-slate-950">
        <Header/>
        <main>
          <VideoGrid video={userVideo.data} />
        </main>
      </section>
    </>
  );
};

export default Home;

